process.env['NODE_ENV'] = 'test'
process.env['DATABASE_URL'] = 'postgresql://test:test@localhost:5432/test'
process.env['REDIS_URL'] = 'redis://localhost:6379'
process.env['JWT_SECRET'] = 'test-secret-minimum-32-characters-long!!!'
process.env['API_PORT'] = '4001'
process.env['NEXTAUTH_URL'] = 'http://localhost:3000'
process.env['UPLOADS_PATH'] = '/tmp/uploads'
